### ISSUE TITLE
Validate message contents from Bitbucket contain the relevant information

### ISSUE THREAD

**Issue by buep** [Praqma/tracey-bitbucket-eiffel-rabbitmq-post-receive-hook#20]
This is something that is already implemented, we just want another look at the date.

Just try to check the message content using this description when doing local debug: https://github.com/Praqma/tracey-developer-environment#debugging-messages

Post an example here on a message.

**Comment by kryptag** [comment]
<img width="1440" alt="screen shot 2017-12-20 at 11 08 26" src="https://user-images.githubusercontent.com/11290150/34201856-2f4175a2-e576-11e7-9541-0387070d184b.png">

Still seems to work as Andrey made it, even after changing to user defined config instead of defaults.
