### ISSUE TITLE
Try to install the unpublished plugin on a bitbucket 5.4.0 server

### ISSUE THREAD

**Issue by buep** [Praqma/tracey-bitbucket-eiffel-rabbitmq-post-receive-hook#21]
Just to see if there is any breaking things compared to our dev environment where we will validate it can install on later version (#19).

**Comment by buep** [comment]
For internal use it is easy to use Team In Space for testing with older version. Download the source, edit the product specification configuration file and rebuild the docker image locally and use that.

**Comment by kryptag** [comment]
@buep We are having some problems with deploying it in teams_in_space, so i will create a new issue to fix the problems and then come back to this one

**Comment by buep** [comment]
I think we can close this - we know there are problems, see #24 adn #27 and we hope to fix them now after we did #27 as part of the delivery for #26 .
