### ISSUE TITLE
Password visible in cleartext when configuration repository

### ISSUE THREAD

**Issue by RandomSort** [Praqma/tracey-bitbucket-eiffel-rabbitmq-post-receive-hook#32]
password is visible in plaintext when configuring a repository.
![image](https://user-images.githubusercontent.com/582571/35504627-d39bccba-04e3-11e8-99c7-3945561f2cf9.png)

It should be dots, asterixes or something of that ilk.

**Comment by buep** [comment]
duplicate #31
