### ISSUE TITLE
Plugin seems to send four messages per commit

### ISSUE THREAD

**Issue by RandomSort** [Praqma/tracey-bitbucket-eiffel-rabbitmq-post-receive-hook#36]
Hard for me to figure out if this is on purpose. But it seems a bit off :)

**Comment by buep** [comment]
It should send exactly one SourceChangeCreated event message. So let's debug this together when we meet and report back on this issue.

**Comment by RandomSort** [comment]
Today I only get one message per commit - so it might be temporary, I will try to grab logs if I see this behaviour again. For me you can close this issue and I will reopen this if it happens again.
